# 8 月 24 日

## rCore-SMP

发现昨天处理器数组的问题是我不小心在 os/src/main.rs 中将其初始化两次。

有个麻烦问题是文件系统的并发部分。一般的文件系统是怎么处理的呢？似乎多进程同时写一个文件，不共享文件描述符时，OS 并没有太多的干预。我们也先不处理这种情况了。

接下来还有个对终端输入的并发读问题。为了简单，我们让 backup hart 核不再启动那个 ch8b_initproc 了，而是等待其他核来分配任务。由于不同任务间存在父子关系，我们让系统只有一个 init 进程。

感觉现有的栈回溯也并不很好用，莫名其妙崩溃了也找不到原因……

决定从 ```TASK_MANAGER``` 入手，改成每个 Hart 一个 TASK_MANAGER 后，系统不崩溃了。

接下来，本来想着要自己补充相关的系统调用的，然而似乎在前面的实验中已经实现了不少了。我打算直接从 os/src/task/manager.rs 里的 ```add_task``` 入手修改，找到最空闲的 Hart 然后把 ```Arc<TaskControlBlock>``` 加入其中。

配套地，我们也对 os/src/sync/smp.rs 做了一些修改，加入了 ```get``` 和 ```get_mut``` 这两个方法以从文件外部访问结构体的内部。由于我之前没学过模块这些东西，现在还不清楚为什么在这个文件里就能直接访问结构体里私有的字段。修改后，又有如下运行结果：

```text
>> ch5b_forktree
Start_time in run_next_task=8873
pid2: 
Start_time in run_next_task=8877
pid3: 0
Start_time in run_nextStart_time in run_n_ext_task=8878
task=8877
Start_time in run_next_task=8878
*_* Tid 0 calling exit_current_and_run_next
pid4: 1
pid5: 00
pid6: 01
[kernel] Hart 2 panicked at src/sync/up.rs:37 called `Result::unwrap()` on an `Err` value: BorrowMutError
[kernel] Hart 3 panicked at src/sync/up.rs:37 called `Result::unwrap()` on an `Err` value: BorrowMutError
[kernel] Hart 0 panicked at src/sync/up.rs:37 called `Result::unwrap()` on an `Err` value: BorrowMutError
---START BACKTRACE---
a0=33640
From start: sp=0xfffffffffffecd70
[DEBUG] trap_from_kernel: Sstatus::spp is Supervisor.
[kernel] Hart 2 panicked at src/trap/mod.rs:198 trap_from_kernel: Exception(StorePageFault) in kernel, bad addr = 0xfffffffffffed000, bad instruction = 0x0.
*_* Tid 0 calling exit_current_and_run_next
[kernel] Hart 1 panicked at src/sync/up.rs:37 called `Result::unwrap()` on an `Err` value: BorrowMutError
QEMU: Terminated
```

这里和页表有关的 Fault 提醒我，是不是要切换到这个进程的页表呢？不过我还是先改一下简单的 ```PID_ALLOCATOR``` 试一下。不过好像并没有本质上的改变。

## 总结

一时间又陷入了困境中。可能要重新查找一下存在的问题，比如栈回溯是否真的工作正常。