# 9 月 13 日

## rCore-SMP

痛定思痛，今天又把这个项目捡起来了。

暂时搁置 backtrace 的事后，发现 os/src/timer.rs 中的 ```static ref TIMERS: UPSafeCell<BinaryHeap<TimerCondVar>>``` 有并发问题，就把它改成每个核各一个了。

不少崩溃的栈回溯里一直有 ```os::syscall::process::sys_waitpid```，但之后就直接跳到 ```os::lang_items::backtrace``` 了。在 os/src/task/process.rs 中将 ```inner_exclusive_access``` 用 ```#[inline(never)]``` 标记后再次尝试，结果有了进展：

```text
黄色
Stack size 400, ra 0x802295ac, sp 0xffffffffffffea90, ins 0x80229d34
0x80229402 (+426) os::lang_items::backtrace
Stack size 448, ra 0x80208452, sp 0xffffffffffffec20, ins 0x80229402
0x80208428 (+42) os::task::process::ProcessControlBlock::inner_exclusive_access
Stack size 32, ra 0x80223f26, sp 0xffffffffffffede0, ins 0x80208428
0x80223e26 (+256) os::syscall::process::sys_waitpid
Stack size 160, ra 0x80210842, sp 0xffffffffffffee00, ins 0x80223e26
0x80210622 (+544) os::syscall::syscall
Stack size 176, ra 0x802154b8, sp 0xffffffffffffeea0, ins 0x80210622
0x80215356 (+354) trap_handler
Stack size 176, ra 0x3e0, sp 0xffffffffffffef50, ins 0x80215356
first_ins: 0x113 0b100010011
Outer loop: stack_size=0x3b0, ra=0x802295f4, sp=0xffffffffffffe870, ins=0x8022a1b0
红色
Stack size 400, ra 0x802295ac, sp 0xfffffffffffe9900, ins 0x80229d34
0x80229402 (+426) os::lang_items::backtrace
Stack size 448, ra 0x80208452, sp 0xfffffffffffe9a90, ins 0x80229402
0x80208428 (+42) os::task::process::ProcessControlBlock::inner_exclusive_access
Stack size 32, ra 0x80218722, sp 0xfffffffffffe9c50, ins 0x80208428
0x8021835c (+966) os::task::exit_current_and_run_next
Stack size 416, ra 0x802235e6, sp 0xfffffffffffe9c70, ins 0x8021835c
0x802234ce (+280) os::syscall::process::sys_exit
Stack size 144, ra 0x80210b04, sp 0xfffffffffffe9e10, ins 0x802234ce
0x80210622 (+1250) os::syscall::syscall
Stack size 176, ra 0x802154b8, sp 0xfffffffffffe9ea0, ins 0x80210622
0x80215356 (+354) trap_handler
Stack size 176, ra 0x3084, sp 0xfffffffffffe9f50, ins 0x80215356
first_ins: 0x113 0b100010011
Outer loop: stack_size=0x3b0, ra=0x802295f4, sp=0xfffffffffffe96e0, ins=0x8022a1b0
```

推断，应该是 ```os::task::exit_current_and_run_next``` 和 ```os::syscall::process::sys_waitpid``` 发生了竞争。通过进一步调试（我只会 `println`），发现，```sys_waitpid``` 中相关代码为：

```rust
let pair = inner.children.iter().enumerate().find(|(_, p)| {
    // ++++ temporarily access child PCB exclusively
    p.inner_exclusive_access().is_zombie && (pid == -1 || pid as usize == p.getpid())
    // ++++ release child PCB
});
```

而 ```exit_current_and_run_next``` 中相关代码为：

```rust
let mut initproc_inner = INITPROC.inner_exclusive_access();
```

观察了一下，```INITPROC``` 也存在并发问题，因为进程退出时要把孤儿进程放到其下面作为其子进程。修改了这个地方后，还在 ```sys_waitpid``` 同一位置处崩溃。看起来同时访问了 ```inner```。有没有可能是 ```children``` 设计上的缺陷，children 指向的 ProcessControlBlock 是 Arc 的而没经过 SMPSafeCell 之类的控制，访问子进程时没有考虑并发的情况？

后来考虑了一下，```Arc``` 是线程安全的，但仅限于在全部指针离开作用域时释放。（这里我们可能在与 Send 和 Sync 的结合上的实现上有些问题）我们计划与 ```SMPSafeCell``` 等结合一下。

## 总结

最近时间不多了，看看什么时候能进一步推进。